services:
  - type: web
    name: backend-service
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip && pip3 install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
